### PR TITLE
CC-1239: Extract inspectable_byte_string to tester_utils

### PR DESCRIPTION
**Pull request by ryan-gang**

### CODE REVIEW

**Review by rohitpaulk — CHANGES_REQUESTED** [review]
failing tests

**Comment by ryan-gang** [comment]
(Go version mismatch)

**Comment by ryan-gang** [comment]
(Go version mismatch)

**Comment by rohitpaulk** [comment]
@ryan-gang still needs to be fixed

**Comment by ryan-gang** [comment]
I have updated the go.mod to use Go 1.21, should I also update the test.yml file to use the same version ? 
(One of the functions we use `max` needs the updated version).

**Comment by rohitpaulk** [comment]
Figure out please, this doesn't seem like something you need my help on

**Review by rohitpaulk — APPROVED** [review]

**Pull request merged**
